name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy code to Raspberry Pi
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            cd /home/aayanh/mc-discbot/mc-helper-discbot &&
            git pull &&
            echo 'Bot pulled successfully!'
          "
