name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Key Auth
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -vvv -o StrictHostKeyChecking=no -i key.pem ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "echo SUCCESS"

